### ISSUE TITLE
{suggestion} ox-lib menu 

### ISSUE THREAD

**Issue by bbeckann** [esx-framework/esx_taxijob#18]
Hey . I'm making a suggestion here. I would love to see an option to use the ox menu from oxlib, this integration with the ox menu will be very intuitive.

![image](https://user-images.githubusercontent.com/95275692/230506190-439e62c5-8c09-448c-a60d-4a91c155997e.png)

**Comment by TheFantomas** [comment]
Hello,

In the current state, this script will not be added to our scripts, or rather, we will not add any third-party scripts to our scripts.

Still, thank you for this suggestion and for trying to improve our framework with your suggestion.

Sincerely, respectfully
Management/Leadert of ESX Legacy Team
Fantík
