### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by leonk193** [esx-framework/esx_taxijob#34]
Hi, I get this error:
![image](https://github.com/user-attachments/assets/15d90ca2-295b-4107-a416-9f86d3322e21)

**Comment by Arctos2win** [comment]
Hi @leonk193, 

You probably have a syntax error in the Config file 
which happens when you for example forget to close a table or 
forget a , 

Try to find the syntax error or put the default config back in and do the changes 
again. 

Greetings 
- @Arctos2win
