### ISSUE TITLE
Players can start NPC Job in taxi and take other vehicle and work job :) 

### ISSUE THREAD

**Issue by Tinky124** [esx-framework/esx_taxijob#46]

**Comment by BrakingESX247** [comment]
Still having issues?

**Comment by Tinky124** [comment]
yes

**Comment by HumanTree92** [comment]
Could simply set up a check so when someone starts a NPC Mission that every so often it will check the players vehicle. And if the player isn't in a Taxi it cancels the mission.

**Comment by BrakingESX247** [comment]
@Tinky124 Can you test now with the most recent commit?

**Comment by Tinky124** [comment]
yes i can

**Comment by Tinky124** [comment]
working
